/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 testBDMascotbetter.glb --transform
*/

import React, { useRef } from 'react'
import { PresentationControls, useGLTF } from "@react-three/drei";

export function TestMascot(props) {
  const { nodes, materials } = useGLTF('/Model/testBDMascotbetter-transformed.glb')
  const ref = useRef();
  return (
    <group ref={ref}
    position={[window.innerWidth < 750 ? 0 : 10, -8.5, -48.4]}
    scale={0.7} {...props} dispose={null}>
      <PresentationControls
        polar={[0, 0]} // Vertical limits
      >
        <mesh geometry={nodes.Curve002.geometry} material={materials['Material.077']} position={[-1.65, 6.166, 5.585]} rotation={[Math.PI / 2, 0, -0.01]} scale={62.324} />
      <mesh geometry={nodes.Cube009.geometry} material={materials['Material.107']} position={[-9.516, 19.272, 4.625]} rotation={[Math.PI, 0, Math.PI]} scale={[1.771, 2.217, 1.595]} />
      <mesh geometry={nodes.Body001.geometry} material={materials['Body.002']} position={[-0.894, 6.631, 2.488]} scale={4.872} />
      </PresentationControls>
      
    </group>
  )
}

useGLTF.preload('/testBDMascotbetter-transformed.glb')
